services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1112:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      PYTHONUNBUFFERED: "1"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "1111:80"
